#+-----------------------------------+
#| Created by: fgatto13 @2026-02-06  |
#+-----------------------------------+

import azure.functions as func
import logging
import json
import uuid # this module allows for the creation of unique patient IDs
from helper import parse_jwt, log_auth_heaeder

app = func.FunctionApp(http_auth_level=func.AuthLevel.ANONYMOUS)

# the first function is to get the patient data from ID
@app.route(route="patients/{patient_id}", methods=["GET"])
def get_patient(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('get_patient endpoint called')

    # now let's retrieve the patient id from the request
    patient_id = req.route_params.get("patient_id")

    if not patient_id:
        return func.HttpResponse(
            "Missing patient_id",
            status_code=400
        )

    # Placeholder for Entra ID token validation:
    # - it'll extract auth header
    # - validate JWT
    # - check role
    auth_header = req.headers.get("Authorization")
    log_auth_heaeder(auth_header)

    # template for the patient from FHIR call
    patient_data = {
        "resourceType": "Patient",
        "id": patient_id,
        "name": [
            {
                "family": "Rossi",
                "given": ["Mario"]
            }
        ],
        "gender": "male",
        "birthDate": "1980-01-01"
    }

    return func.HttpResponse(
        body=json.dumps(patient_data),
        status_code=200,
        mimetype="application/json"
    )

# this function is to get a list of patients
@app.route(route="patients", methods=["GET"])
def list_patients(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("list_patients endpoint called")

    # validates Entra ID
    auth_header = req.headers.get("Authorization")
    log_auth_heaeder(auth_header)

    # gets data from FHIR

    # FHIR bundle data template for testing purposes (mocked up response)
    patients_bundle = {
        "resourceType": "Bundle",
        "type": "searchset",
        "total": 2,
        "entry": [
            {
                "resource": {
                    "resourceType": "Patient",
                    "id": "1",
                    "name": [{"family": "Rossi", "given": ["Mario"]}],
                    "gender": "male"
                }
            },
            {
                "resource": {
                    "resourceType": "Patient",
                    "id": "2",
                    "name": [{"family": "Bianchi", "given": ["Luisa"]}],
                    "gender": "female"
                }
            }
        ]
    }

    return func.HttpResponse(
        json.dumps(patients_bundle),
        status_code=200,
        mimetype="application/json"
    )

# this function updates a patient
@app.route(route="patients/{patient_id}", methods=["PUT"])
def update_patient(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("update_patient endpoint called")

    patient_id = req.route_params.get("patient_id")

    if not patient_id:
        return func.HttpResponse(
            "Missing patient_id",
            status_code=400
        )

    try:
        patient_payload = req.get_json()
    except ValueError:
        return func.HttpResponse(
            "Invalid JSON body",
            status_code=400
        )

    # FHIR sanity checks
    if patient_payload.get("resourceType") != "Patient":
        return func.HttpResponse(
            "Payload must be a Patient resource",
            status_code=400
        )

    if patient_payload.get("id") != patient_id:
        return func.HttpResponse(
            "Patient ID mismatch between URL and body",
            status_code=400
        )

    # PLACEHOLDER: Entra ID validation
    auth_header = req.headers.get("Authorization")
    log_auth_heaeder(auth_header)

    # PLACEHOLDER: FHIR PUT
    # PUT /Patient/{id}

    updated_patient = patient_payload  # mock behavior

    return func.HttpResponse(
        body=json.dumps(updated_patient),
        status_code=200,
        mimetype="application/json"
    )

# this function allows for the creation of a new patient
@app.route(route="patients", methods=["POST"])
def create_patient(req: func.HttpRequest) -> func.HttpResponse:
    logging.info("create_patient endpoint called")

    try:
        patient_payload = req.get_json()
    except ValueError:
        return func.HttpResponse(
            "Invalid JSON body",
            status_code=400
        )

    # FHIR sanity checks
    if patient_payload.get("resourceType") != "Patient":
        return func.HttpResponse(
            "Payload must be a Patient resource",
            status_code=400
        )

    if "id" in patient_payload:
        return func.HttpResponse(
            "New Patient cannot include an ID; it will be generated by the server",
            status_code=400
        )

    # PLACEHOLDER: Entra ID validation
    # - Ensure role = Doctor / Admin
    auth_header = req.headers.get("Authorization")
    log_auth_heaeder(auth_header)

    # PLACEHOLDER: FHIR POST
    # This will eventually call:
    # POST /Patient

    # Generate a mock patient ID
    new_patient_id = str(uuid.uuid4())
    patient_payload["id"] = new_patient_id

    # Mock creation response
    created_patient = patient_payload

    return func.HttpResponse(
        body=json.dumps(created_patient),
        status_code=201,
        mimetype="application/json"
    )